# Generated by Django 6.1 on 2026-08-31 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('escalation_level', models.PositiveSmallIntegerField(choices=[(1, 'Primary Guardian'), (2, 'Secondary Guardian'), (3, 'Emergency Contact')], default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Set if this contact is also a registered app user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarding', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['escalation_level', 'order'],
                'constraints': [models.UniqueConstraint(fields=('resident', 'escalation_level', 'order'), name='uniq_contact_slot')],
            },
        ),
    ]
