# Generated by Django 6.1 on 2026-08-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_available_emergencycontact'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='society',
            field=models.ForeignKey(blank=True, help_text='Society this user belongs to. Drives alert routing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='societies.society'),
        ),
    ]
